/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-10-27 07:36:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1634537052956L));
    _jspx_dependants.put("jar:file:/C:/Users/kwang/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/oct_8_spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"contaner\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-4\"></div>\r\n");
      out.write("			<div class=\"col-4\"><br><br>\r\n");
      out.write("				<form method=\"post\" action=\"/signUp\" id =\"signUpForm\">\r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"exampleInputEmail1\" class=\"form-label\">id</label>\r\n");
      out.write("				    <input type=\"text\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" name=\"mi_id\"  >\r\n");
      out.write("				    <div id=\"id_check\"></div>\r\n");
      out.write("				    \r\n");
      out.write("				  </div>\r\n");
      out.write("				  \r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\r\n");
      out.write("				    <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" name=\"mi_pw\">\r\n");
      out.write("				    <div id=\"pw1_check\"></div>\r\n");
      out.write("				  </div>\r\n");
      out.write("				  \r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"exampleInputPassword2\" class=\"form-label\">PasswordCheck</label>\r\n");
      out.write("				    <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword2\">\r\n");
      out.write("				    <div id=\"pw2_check\"></div>\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"mobile\" class=\"form-label\">mobile</label>\r\n");
      out.write("				    <input type=\"text\" class=\"form-control\" name=\"mi_mobile\" id=\"mobile\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"email\" class=\"form-label\">email</label>\r\n");
      out.write("				    <input type=\"email\" class=\"form-control\" id=\"email\" name=\"mi_email\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  \r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"m\" class=\"form-label\">m</label>\r\n");
      out.write("				    <input type=\"radio\" class=\" gender\" id=\"m\" name=\"gender\" value=\"M\">\r\n");
      out.write("				    \r\n");
      out.write("				    <label for=\"w\" class=\"form-label\">w</label>\r\n");
      out.write("				    <input type=\"radio\" class=\" gender\" id=\"w\" name=\"gender\" value=\"W\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  \r\n");
      out.write("				  \r\n");
      out.write("				  \r\n");
      out.write("				  <button type=\"button\" class=\"btn btn-primary\" id=\"check-btn\">회원가입</button>\r\n");
      out.write("				  <a href=\"#\" class=\"btn btn-primary\">취소하기</a>\r\n");
      out.write("				</form>\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-4\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var initialize = function(){\r\n");
      out.write("			var idReg = /^[a-z]+[a-z0-9]{5,19}$/g;\r\n");
      out.write("			var id = $(\"#exampleInputEmail1\").val();\r\n");
      out.write("			var pw1 = $(\"#exampleInputPassword1\").val();\r\n");
      out.write("			var pw2 = $(\"#exampleInputPassword2\").val();\r\n");
      out.write("			var check = {\r\n");
      out.write("				\"pw2\" : false,\r\n");
      out.write("				\"pw1\" : false,\r\n");
      out.write("				\"id\" : false\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			//유효성검사 \r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$(\"#exampleInputEmail1\").on(\"input\", function () {\r\n");
      out.write("				var idReg = /^[a-z]+[a-z0-9]{5,19}$/g;\r\n");
      out.write("				var id = $(\"#exampleInputEmail1\").val();\r\n");
      out.write("				if(idReg.test(id)){\r\n");
      out.write("					\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						type : \"post\",\r\n");
      out.write("						data : {\r\n");
      out.write("							mi_id : id\r\n");
      out.write("						},\r\n");
      out.write("						url : \"/checkId\",\r\n");
      out.write("						success : function(res){\r\n");
      out.write("							if(res.result == 0){\r\n");
      out.write("								$(\"#id_check\").text(\"사용 가능한 아이디입니다\").css(\"color\",\"green\");\r\n");
      out.write("								check.id = true;\r\n");
      out.write("								console.log(check)\r\n");
      out.write("							}else{\r\n");
      out.write("								$(\"#id_check\").text(\"사용중인 아이디입니다\").css(\"color\",\"red\");\r\n");
      out.write("								check.id = false;\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#id_check\").text(\"유효하지 않는 아이디입니다\").css(\"color\",\"red\");\r\n");
      out.write("					check.id = false;\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$(\"#exampleInputPassword1\").on(\"input\",function(){\r\n");
      out.write("				var idReg = /^[a-z]+[a-z0-9]{5,19}$/g;\r\n");
      out.write("				var pw1 = $(\"#exampleInputPassword1\").val();\r\n");
      out.write("				if(idReg.test(pw1)){\r\n");
      out.write("					$(\"#pw1_check\").text(\"사용 가능한 비밀번호입니다\").css(\"color\",\"green\");\r\n");
      out.write("					check.pw1 = true;\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#pw1_check\").text(\"사용 불가능한 비밀번호입니다\").css(\"color\",\"red\");\r\n");
      out.write("					check.pw1 = false;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			$(\"#exampleInputPassword2\").on(\"input\",function(){\r\n");
      out.write("				\r\n");
      out.write("				var idReg = /^[a-z]+[a-z0-9]{5,19}$/g;\r\n");
      out.write("				var pw1 = $(\"#exampleInputPassword1\").val();\r\n");
      out.write("				var pw2 = $(\"#exampleInputPassword2\").val();\r\n");
      out.write("				\r\n");
      out.write("				if(idReg.test(pw2) && pw1 === pw2 ){\r\n");
      out.write("					$(\"#pw2_check\").text(\"사용 가능한 비밀번호입니다\").css(\"color\",\"green\");\r\n");
      out.write("					check.pw2 = true;\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#pw2_check\").text(\"사용 불가능한 비밀번호입니다\").css(\"color\",\"red\");\r\n");
      out.write("					check.pw2 = false;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			$(\"#check-btn\").on(\"click\", function () {\r\n");
      out.write("				\r\n");
      out.write("				var bool = true;\r\n");
      out.write("				for(var key in check){\r\n");
      out.write("					if(!check[key]){\r\n");
      out.write("						var msg = \"\";\r\n");
      out.write("						switch(key){\r\n");
      out.write("							\r\n");
      out.write("							case \"id\" :\r\n");
      out.write("								msg = \"유효하지 않은 아이디입니다\";\r\n");
      out.write("								bool = false;\r\n");
      out.write("								break;\r\n");
      out.write("							case \"pw2\" :\r\n");
      out.write("								msg =\"유효하지 않은 비밀번호2입니다\";\r\n");
      out.write("								bool = false;\r\n");
      out.write("								break;\r\n");
      out.write("							case \"pw1\" :\r\n");
      out.write("								msg =\"유효하지 않은 비밀번호1입니다\";\r\n");
      out.write("								bool = false;\r\n");
      out.write("								break;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				if(bool){\r\n");
      out.write("					$(\"#signUpForm\").submit();\r\n");
      out.write("				}else{\r\n");
      out.write("					alert(msg);\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			 \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\n");
      out.write("	</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
