/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-10-19 02:44:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<main class=\"container\">\r\n");
      out.write("  <div class=\"p-4 p-md-5 mb-4 text-white rounded bg-dark\">\r\n");
      out.write("    <div class=\"col-md-6 px-0\">\r\n");
      out.write("      <h1 class=\"display-4 fst-italic\">Title of a longer featured blog post</h1>\r\n");
      out.write("      <p class=\"lead my-3\">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>\r\n");
      out.write("      <p class=\"lead mb-0\"><a href=\"#\" class=\"text-white fw-bold\">Continue reading...</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row mb-2\">\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\r\n");
      out.write("        <div class=\"col p-4 d-flex flex-column position-static\">\r\n");
      out.write("          <strong class=\"d-inline-block mb-2 text-primary\">World</strong>\r\n");
      out.write("          <h3 class=\"mb-0\">Featured post</h3>\r\n");
      out.write("          <div class=\"mb-1 text-muted\">Nov 12</div>\r\n");
      out.write("          <p class=\"card-text mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\r\n");
      out.write("          <a href=\"#\" class=\"stretched-link\">Continue reading</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-auto d-none d-lg-block\">\r\n");
      out.write("          <svg class=\"bd-placeholder-img\" width=\"200\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"#55595c\"></rect><text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\r\n");
      out.write("        <div class=\"col p-4 d-flex flex-column position-static\">\r\n");
      out.write("          <strong class=\"d-inline-block mb-2 text-success\">Design</strong>\r\n");
      out.write("          <h3 class=\"mb-0\">Post title</h3>\r\n");
      out.write("          <div class=\"mb-1 text-muted\">Nov 11</div>\r\n");
      out.write("          <p class=\"mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\r\n");
      out.write("          <a href=\"#\" class=\"stretched-link\">Continue reading</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-auto d-none d-lg-block\">\r\n");
      out.write("          <svg class=\"bd-placeholder-img\" width=\"200\" height=\"250\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Thumbnail\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"#55595c\"></rect><text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row g-5\">\r\n");
      out.write("    <div class=\"col-md-8\">\r\n");
      out.write("      <h3 class=\"pb-4 mb-4 fst-italic border-bottom\">\r\n");
      out.write("        From the Firehose\r\n");
      out.write("      </h3>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"blog-post\">\r\n");
      out.write("        <h2 class=\"blog-post-title\">Sample blog post</h2>\r\n");
      out.write("        <p class=\"blog-post-meta\">January 1, 2021 by <a href=\"#\">Mark</a></p>\r\n");
      out.write("\r\n");
      out.write("        <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, lists, tables, images, code, and more are all supported as expected.</p>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <h2>Blockquotes</h2>\r\n");
      out.write("        <p>This is an example blockquote in action:</p>\r\n");
      out.write("        <blockquote class=\"blockquote\">\r\n");
      out.write("          <p>Quoted text goes here.</p>\r\n");
      out.write("        </blockquote>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <h3>Example lists</h3>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout. This is an example unordered list:</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>First list item</li>\r\n");
      out.write("          <li>Second list item with a longer description</li>\r\n");
      out.write("          <li>Third list item to close it out</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>And this is an ordered list:</p>\r\n");
      out.write("        <ol>\r\n");
      out.write("          <li>First list item</li>\r\n");
      out.write("          <li>Second list item with a longer description</li>\r\n");
      out.write("          <li>Third list item to close it out</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <p>And this is a definition list:</p>\r\n");
      out.write("        <dl>\r\n");
      out.write("          <dt>HyperText Markup Language (HTML)</dt>\r\n");
      out.write("          <dd>The language used to describe and define the content of a Web page</dd>\r\n");
      out.write("          <dt>Cascading Style Sheets (CSS)</dt>\r\n");
      out.write("          <dd>Used to describe the appearance of Web content</dd>\r\n");
      out.write("          <dt>JavaScript (JS)</dt>\r\n");
      out.write("          <dd>The programming language used to build advanced Web sites and applications</dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <h2>Inline HTML elements</h2>\r\n");
      out.write("        <p>HTML defines a long list of available inline tags, a complete list of which can be found on the <a href=\"https://developer.mozilla.org/en-US/docs/Web/HTML/Element\">Mozilla Developer Network</a>.</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><strong>To bold text</strong>, use <code class=\"language-plaintext highlighter-rouge\">&lt;strong&gt;</code>.</li>\r\n");
      out.write("          <li><em>To italicize text</em>, use <code class=\"language-plaintext highlighter-rouge\">&lt;em&gt;</code>.</li>\r\n");
      out.write("          <li>Abbreviations, like <abbr title=\"HyperText Markup Langage\">HTML</abbr> should use <code class=\"language-plaintext highlighter-rouge\">&lt;abbr&gt;</code>, with an optional <code class=\"language-plaintext highlighter-rouge\">title</code> attribute for the full phrase.</li>\r\n");
      out.write("          <li>Citations, like <cite>— Mark Otto</cite>, should use <code class=\"language-plaintext highlighter-rouge\">&lt;cite&gt;</code>.</li>\r\n");
      out.write("          <li><del>Deleted</del> text should use <code class=\"language-plaintext highlighter-rouge\">&lt;del&gt;</code> and <ins>inserted</ins> text should use <code class=\"language-plaintext highlighter-rouge\">&lt;ins&gt;</code>.</li>\r\n");
      out.write("          <li>Superscript <sup>text</sup> uses <code class=\"language-plaintext highlighter-rouge\">&lt;sup&gt;</code> and subscript <sub>text</sub> uses <code class=\"language-plaintext highlighter-rouge\">&lt;sub&gt;</code>.</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>Most of these elements are styled by browsers with few modifications on our part.</p>\r\n");
      out.write("        <h2>Heading</h2>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <h3>Sub-heading</h3>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <pre><code>Example code block</code></pre>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"blog-post\">\r\n");
      out.write("        <h2 class=\"blog-post-title\">Another blog post</h2>\r\n");
      out.write("        <p class=\"blog-post-meta\">December 23, 2020 by <a href=\"#\">Jacob</a></p>\r\n");
      out.write("\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <blockquote>\r\n");
      out.write("          <p>Longer quote goes here, maybe with some <strong>emphasized text</strong> in the middle of it.</p>\r\n");
      out.write("        </blockquote>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <h3>Example table</h3>\r\n");
      out.write("        <p>And don't forget about tables in these posts:</p>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("          <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>Name</th>\r\n");
      out.write("              <th>Upvotes</th>\r\n");
      out.write("              <th>Downvotes</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("          <tbody>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Alice</td>\r\n");
      out.write("              <td>10</td>\r\n");
      out.write("              <td>11</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Bob</td>\r\n");
      out.write("              <td>4</td>\r\n");
      out.write("              <td>3</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Charlie</td>\r\n");
      out.write("              <td>7</td>\r\n");
      out.write("              <td>9</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </tbody>\r\n");
      out.write("          <tfoot>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Totals</td>\r\n");
      out.write("              <td>21</td>\r\n");
      out.write("              <td>23</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </tfoot>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <article class=\"blog-post\">\r\n");
      out.write("        <h2 class=\"blog-post-title\">New feature</h2>\r\n");
      out.write("        <p class=\"blog-post-meta\">December 14, 2020 by <a href=\"#\">Chris</a></p>\r\n");
      out.write("\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>First list item</li>\r\n");
      out.write("          <li>Second list item with a longer description</li>\r\n");
      out.write("          <li>Third list item to close it out</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"blog-pagination\" aria-label=\"Pagination\">\r\n");
      out.write("        <a class=\"btn btn-outline-primary\" href=\"#\">Older</a>\r\n");
      out.write("        <a class=\"btn btn-outline-secondary disabled\">Newer</a>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <div class=\"position-sticky\" style=\"top: 2rem;\">\r\n");
      out.write("        <div class=\"p-4 mb-3 bg-light rounded\">\r\n");
      out.write("          <h4 class=\"fst-italic\">About</h4>\r\n");
      out.write("          <p class=\"mb-0\">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"p-4\">\r\n");
      out.write("          <h4 class=\"fst-italic\">Archives</h4>\r\n");
      out.write("          <ol class=\"list-unstyled mb-0\">\r\n");
      out.write("            <li><a href=\"#\">March 2021</a></li>\r\n");
      out.write("            <li><a href=\"#\">February 2021</a></li>\r\n");
      out.write("            <li><a href=\"#\">January 2021</a></li>\r\n");
      out.write("            <li><a href=\"#\">December 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">November 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">October 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">September 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">August 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">July 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">June 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">May 2020</a></li>\r\n");
      out.write("            <li><a href=\"#\">April 2020</a></li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"p-4\">\r\n");
      out.write("          <h4 class=\"fst-italic\">Elsewhere</h4>\r\n");
      out.write("          <ol class=\"list-unstyled\">\r\n");
      out.write("            <li><a href=\"#\">GitHub</a></li>\r\n");
      out.write("            <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("            <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</main>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
