spring:
  application:
    name: config
  config:
    import:
      - configserver:http://localhost:8888
#      - optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env