/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-10-27 01:17:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"contaner\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-2\"></div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("				  <thead>\r\n");
      out.write("				    <tr>\r\n");
      out.write("				      <th scope=\"col\">국내 확진자수</th>\r\n");
      out.write("				      <th scope=\"col\">국내 완치자수</th>\r\n");
      out.write("				      <th scope=\"col\">국내 사망자수</th>\r\n");
      out.write("				      <th scope=\"col\">국내 격리자수</th>\r\n");
      out.write("				    </tr>\r\n");
      out.write("				  </thead>\r\n");
      out.write("				  <tbody id=\"total\">\r\n");
      out.write("				  \r\n");
      out.write("				   \r\n");
      out.write("				  </tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				\r\n");
      out.write("				<div >\r\n");
      out.write("					<canvas id=\"myChart\" width=\"400px\" height=\"400px\"></canvas>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-2\"></div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\"> \r\n");
      out.write("		<canvas id=\"myChart\"></canvas> \r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<select class=\"form-select\" aria-label=\"Default select example\">\r\n");
      out.write("			  <option selected>지역을 선택해주세요</option>\r\n");
      out.write("			  <option value=\"seoul\">서울</option>\r\n");
      out.write("			  <option value=\"busan\">부산</option>\r\n");
      out.write("			  <option value=\"gyeonggi\">경기</option>\r\n");
      out.write("			  <option value=\"chungbuk\">충북</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<table class=\"table\">\r\n");
      out.write("				  <thead>\r\n");
      out.write("				    <tr>\r\n");
      out.write("				      <th scope=\"col\">시도명</th>\r\n");
      out.write("				      <th scope=\"col\">신규확진환자수</th>\r\n");
      out.write("				      <th scope=\"col\">확진환자수</th>\r\n");
      out.write("				      <th scope=\"col\">완치자수</th>\r\n");
      out.write("				      <th scope=\"col\">사망자</th>\r\n");
      out.write("				    </tr>\r\n");
      out.write("				  </thead>\r\n");
      out.write("				  <tbody id=\"local-tbody\">\r\n");
      out.write("				  \r\n");
      out.write("				   \r\n");
      out.write("				  </tbody>\r\n");
      out.write("				</table>		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(\".form-select\").on(\"change\", function () {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"https://api.corona-19.kr/korea/country/new/?serviceKey=BedTft6H3gDEqN4Z18I7vAmJlcGXxjCki\",\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(value){\r\n");
      out.write("				var m = $(\".form-select option:selected\").val();\r\n");
      out.write("		/* 		console.log(m)\r\n");
      out.write("				console.log(value.m);\r\n");
      out.write("				console.log(value.busan); */\r\n");
      out.write("				console.log(value);\r\n");
      out.write("				\r\n");
      out.write("				$(\"#local-tbody\").children().remove();\r\n");
      out.write("				\r\n");
      out.write("				var html = '';\r\n");
      out.write("				html += '<td>'+value[m].countryName+'</td>';\r\n");
      out.write("				html += '<td>'+value[m].newCase+'</td>';\r\n");
      out.write("				html += '<td>'+value[m].totalCase+'</td>';\r\n");
      out.write("				html += '<td>'+value[m].recovered+'</td>';\r\n");
      out.write("				html += '<td>'+value[m].death+'</td>';\r\n");
      out.write("				\r\n");
      out.write("				$(\"#local-tbody\").append(html);\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	var initialize = function(){\r\n");
      out.write("		var Html = \"\";\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			url : \"https://api.corona-19.kr/korea/?serviceKey=BedTft6H3gDEqN4Z18I7vAmJlcGXxjCki\",\r\n");
      out.write("			success : function(value) {\r\n");
      out.write("				\r\n");
      out.write("				console.log(value);\r\n");
      out.write("				\r\n");
      out.write("				var html = '';\r\n");
      out.write("				\r\n");
      out.write("				html += '<tr>';\r\n");
      out.write("				html += '<td>'+value.TotalCase;\r\n");
      out.write("				html += '</td>';\r\n");
      out.write("				html += '<td>'+value.TotalRecovered;\r\n");
      out.write("				html += '</td>';\r\n");
      out.write("				html += '<td>'+value.TotalDeath;\r\n");
      out.write("				html += '</td>';\r\n");
      out.write("				html += '<td>'+value.NowCase;\r\n");
      out.write("				html += '</td>';\r\n");
      out.write("				html += '</tr>';\r\n");
      out.write("				\r\n");
      out.write("				$(\"#total\").append(html);\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				var ctx = document.getElementById('myChart');\r\n");
      out.write("				var myChart = new Chart(ctx, {\r\n");
      out.write("					type: 'bar',\r\n");
      out.write("					data: {\r\n");
      out.write("						labels: [value.city1n, value.city2n, value.city3n, value.city4n, value.city5n],\r\n");
      out.write("						datasets: [{\r\n");
      out.write("							label: '전국 확진자 top5',\r\n");
      out.write("							data: [value.city1p, value.city2p, value.city3p, value.city4p, value.city5p],\r\n");
      out.write("							backgroundColor: [\r\n");
      out.write("								'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("								'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("								'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("								'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("								'rgba(153, 102, 255, 0.2)'\r\n");
      out.write("							],\r\n");
      out.write("							borderColor: [\r\n");
      out.write("								'rgba(255, 99, 132, 1)',\r\n");
      out.write("								'rgba(54, 162, 235, 1)',\r\n");
      out.write("								'rgba(255, 206, 86, 1)',\r\n");
      out.write("								'rgba(75, 192, 192, 1)',\r\n");
      out.write("								'rgba(153, 102, 255, 1)'\r\n");
      out.write("							],\r\n");
      out.write("							borderWidth: 1\r\n");
      out.write("						}]\r\n");
      out.write("					},\r\n");
      out.write("					options: {\r\n");
      out.write("						responsive: false,\r\n");
      out.write("						scales: {\r\n");
      out.write("							yAxes: [{\r\n");
      out.write("								ticks: {\r\n");
      out.write("									beginAtZero: true\r\n");
      out.write("								}\r\n");
      out.write("							}]\r\n");
      out.write("						},\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\n");
      out.write("\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
