/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-10-25 06:41:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"contaner\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-2\"></div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("			  <thead>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			      <th scope=\"col\">ni_no</th>\r\n");
      out.write("			      <th scope=\"col\">ni_title</th>\r\n");
      out.write("			      <th scope=\"col\">ni_content</th>\r\n");
      out.write("			      <th scope=\"col\">ni_isert_dt</th>\r\n");
      out.write("			      <th scope=\"col\">ni_modifi_dt</th>\r\n");
      out.write("			      <th scope=\"col\">mi_id</th>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			  </thead>\r\n");
      out.write("			  <tbody>\r\n");
      out.write("			    \r\n");
      out.write("			  </tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-2\"></div>\r\n");
      out.write("			<div id=\"pageNav\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"input-group\">\r\n");
      out.write("		  <select class=\"form-select\" id=\"inputGroupSelect04\" aria-label=\"Example select with button addon\">\r\n");
      out.write("		    <option selected value=\"choose\">Choose...</option>\r\n");
      out.write("		    <option value=\"ni_no\" >ni_no</option>\r\n");
      out.write("		    <option value=\"ni_title\">ni_title</option>\r\n");
      out.write("		    <option value=\"ni_content\">ni_content</option>\r\n");
      out.write("		  </select>\r\n");
      out.write("		  <input id=\"search_Keyword\">\r\n");
      out.write("		  <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"search-btn\">Button</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		  <a class=\"btn btn-primary\" href=\"write\" >글쓰기</a>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	var data = {};\r\n");
      out.write("	var initialize = function(){\r\n");
      out.write("		\r\n");
      out.write("		Search(1);\r\n");
      out.write("		$(\"#search-btn\").click(function(){\r\n");
      out.write("			var searchType = $(\"#inputGroupSelect04 option:selected\").val();\r\n");
      out.write("			var searchKeyword = $(\"#search_Keyword\").val();\r\n");
      out.write("			data.search_type = searchType;\r\n");
      out.write("			data.search_key = searchKeyword;\r\n");
      out.write("			Search(1);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		 \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var Search = function(selPage) {\r\n");
      out.write("		\r\n");
      out.write("		data.curPage = selPage;\r\n");
      out.write("		data.pagePerCnt = 10;\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'post',\r\n");
      out.write("			url : \"/notice\",\r\n");
      out.write("			data : {\r\n");
      out.write("				search_type : data.search_type,\r\n");
      out.write("				search_key : data.search_key,\r\n");
      out.write("				curPage : data.curPage,\r\n");
      out.write("				pagePerCnt : data.pagePerCnt\r\n");
      out.write("			},\r\n");
      out.write("			success : function(value) {\r\n");
      out.write("				var notice = value.list;\r\n");
      out.write("				$(\"tbody\").children().remove();\r\n");
      out.write("				var html = \"\";\r\n");
      out.write("				for(var i = 0; i < notice.length; i++){\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					html += '<tr>';\r\n");
      out.write("					html += '<td>' + notice[i].ni_no + '</td>';\r\n");
      out.write("					html += '<td>' +'<a href=/view?ni_no='+notice[i].ni_no+'  >'+ notice[i].ni_title + '</a>'+'</td>';\r\n");
      out.write("					html += '<td>' + notice[i].ni_content + '</td>';\r\n");
      out.write("					html += '<td>' + notice[i].ni_isert_dt + '</td>';\r\n");
      out.write("					html += '<td>' + notice[i].ni_modifi_dt + '</td>';\r\n");
      out.write("					html += '<td>' + notice[i].mi_id + '</td>';\r\n");
      out.write("					html += '</tr>';\r\n");
      out.write("				}				\r\n");
      out.write("				$(\"tbody\").append(html);\r\n");
      out.write("				$(\"#pageNav\").paging({\r\n");
      out.write("					pageSize : data.pagePerCnt,  \r\n");
      out.write("					PAGE_PER_CNT:  data.pagePerCnt, \r\n");
      out.write("					currentPage: data.curPage,\r\n");
      out.write("					pageTotal: value.total\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	var goPage = function(selPage){\r\n");
      out.write("		Search(selPage);\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
