/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-10-26 01:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reple_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1634537052956L));
    _jspx_dependants.put("jar:file:/C:/Users/kwang/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/oct_8_spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <form id=\"commentListForm\" name=\"commentListForm\" method=\"post\">\r\n");
      out.write("        <div id=\"commentList\">\r\n");
      out.write("        	 <div id =\"reset-div\">\r\n");
      out.write("        	 \r\n");
      out.write("        	 <!-- for문 돌릴부분 -->\r\n");
      out.write("                   <div>\r\n");
      out.write("	                    <table class='table'>\r\n");
      out.write("	                   		 <h6><strong>작성자</strong></h6>\r\n");
      out.write("	                   		 <tr>\r\n");
      out.write("	                   		 	<td>댓글 내용</td>\r\n");
      out.write("	                   		 	<td>\r\n");
      out.write("	                   		 		<button class=\"btn btn-primary\">수정</button>\r\n");
      out.write("	                   		 		<button class=\"btn btn-danger\">삭제</button>\r\n");
      out.write("	                   		 	</td>\r\n");
      out.write("	                   		 </tr>\r\n");
      out.write("	                    </table>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <!-- 여기까지 -->\r\n");
      out.write("	                \r\n");
      out.write("	                \r\n");
      out.write("	                \r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("	<div id=\"pageNav\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span><strong>Comments</strong></span> <span id=\"cCnt\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <table class=\"table\">     \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <textarea style=\"width: 1100px\" rows=\"3\" cols=\"30\" id=\"comment\" name=\"comment\" placeholder=\"댓글을 입력하세요\"></textarea>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <button id=\"insert_btn\" class=\"btn pull-right btn-success\" onclick=\"insert()\">등록</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	var ni_no = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.ni_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("	var data = {};\r\n");
      out.write("	var initialize = function(){\r\n");
      out.write("		\r\n");
      out.write("		Search(1);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function insert() {\r\n");
      out.write("		var ri_content = $(\"#comment\").val()\r\n");
      out.write("		console.log(ni_no)\r\n");
      out.write("		console.log(ri_content)\r\n");
      out.write("		/* 여기부터 ajax로 삽입하기! */\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"/reple/insert\",\r\n");
      out.write("			data : {\r\n");
      out.write("				ni_no : ni_no,\r\n");
      out.write("				ri_content : ri_content\r\n");
      out.write("			},\r\n");
      out.write("			success : function(value) {\r\n");
      out.write("				var result = value.result;\r\n");
      out.write("				if(result ==1){\r\n");
      out.write("					Search(1);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	var Search = function(selPage) {\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		data.curPage = selPage;\r\n");
      out.write("		data.pagePerCnt = 10;\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'post',\r\n");
      out.write("			url : \"/reple/list\",\r\n");
      out.write("			data : {\r\n");
      out.write("				ni_no : ni_no,\r\n");
      out.write("				curPage : data.curPage,\r\n");
      out.write("				pagePerCnt : data.pagePerCnt\r\n");
      out.write("			},\r\n");
      out.write("			success : function(value) {\r\n");
      out.write("				var reple = value.list;\r\n");
      out.write("				$(\"#reset-div\").children().remove();\r\n");
      out.write("				var loginMember = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.mi_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				var html = \"\";\r\n");
      out.write("				for(var i = 0; i < reple.length; i++){\r\n");
      out.write("					html += '<div id =\"reple'+i+'\">';\r\n");
      out.write("					html += '<table class=\"table\">';\r\n");
      out.write("					html += '<h6><strong>'+reple[i].mi_id+'</strong></h6>';\r\n");
      out.write("					html += '<tr>';\r\n");
      out.write("					html += '<td>'+reple[i].ri_content+'</td>';\r\n");
      out.write("					html += '<td>';\r\n");
      out.write("					if(loginMember == reple[i].mi_id){\r\n");
      out.write("						html += '<button type=\"button\" class=\"btn btn-primary\" onclick=modify('+reple[i].ri_no+',reple'+i+')>수정</button>';\r\n");
      out.write("						html += '<button type=\"button\" class=\"btn btn-danger\" onclick=delect('+reple[i].ri_no+')>삭제</button>';\r\n");
      out.write("					}\r\n");
      out.write("					html += '</td>';\r\n");
      out.write("					html += '</tr>';\r\n");
      out.write("					html += '</table>';\r\n");
      out.write("					html += '</div> ';\r\n");
      out.write("				}			\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				$(\"#reset-div\").append(html);\r\n");
      out.write("				$(\"#pageNav\").paging({\r\n");
      out.write("					pageSize : data.pagePerCnt,  \r\n");
      out.write("					PAGE_PER_CNT:  data.pagePerCnt, \r\n");
      out.write("					currentPage: data.curPage,\r\n");
      out.write("					pageTotal: value.total\r\n");
      out.write("				}); \r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	var goPage = function(selPage){\r\n");
      out.write("		Search(selPage);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function modify(ri_no, i) {\r\n");
      out.write("		console.log(ri_no);\r\n");
      out.write("		console.log(i.id);\r\n");
      out.write("		var id = i.id;\r\n");
      out.write("		\r\n");
      out.write("		$('#'+id+'').children().remove();\r\n");
      out.write("		var loginMember = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.mi_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("		var html = \"\";\r\n");
      out.write("		\r\n");
      out.write("			html += '<table class=\"table\">';\r\n");
      out.write("			html += '<h6><strong>'+loginMember+'</strong></h6>';\r\n");
      out.write("			html += '<tr>';\r\n");
      out.write("			html += '<input type=\"text\" class=\"input\">';\r\n");
      out.write("			html += '<td>';\r\n");
      out.write("			html += '<button type=\"button\" class=\"btn btn-primary\" onclick=realModify('+ri_no+','+id+')>수정</button>';\r\n");
      out.write("			html += '<button type=\"button\" class=\"btn btn-danger\" onclick=Search(1)>취소</button>';\r\n");
      out.write("			html += '</td>';\r\n");
      out.write("			html += '</tr>';\r\n");
      out.write("			html += '</table>';\r\n");
      out.write("		$('#'+id+'').append(html);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function realModify(ri_no, i) {\r\n");
      out.write("		\r\n");
      out.write("		var id = i.id;\r\n");
      out.write("		\r\n");
      out.write("		var ri_content = $('#'+id+'').children('input').val();\r\n");
      out.write("		console.log(ri_content)\r\n");
      out.write("		console.log(ri_no)\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			data : {\r\n");
      out.write("				ri_content : ri_content,\r\n");
      out.write("				ri_no : ri_no\r\n");
      out.write("			},\r\n");
      out.write("			url : \"/reple/modify\",\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			success : function(value) {\r\n");
      out.write("				var result = value.result;\r\n");
      out.write("				if(result ==1){\r\n");
      out.write("					Search(1);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function delect(ri_no) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			data : {\r\n");
      out.write("				ri_no : ri_no\r\n");
      out.write("			},\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"reple/delect\",\r\n");
      out.write("			success : function(value) {\r\n");
      out.write("				var result = value.result;\r\n");
      out.write("				if(result ==1){\r\n");
      out.write("					Search(1);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
